### ISSUE TITLE
 PARA_BTC_15M.csv is not found

### ISSUE THREAD

**Issue by halfss** [cooltheo17/BinanceBot#1]
hello, this BinanceBot project is very good, but when I run it, I got this, can you help me?

```
root@1111:~/BinanceBot# python statGetter.py
(Time period: 10 days)

Traceback (most recent call last):
  File "statGetter.py", line 12, in <module>
    my_data = genfromtxt('PARA_BTC_15M.csv', delimiter=',')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1744, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 266, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 624, in open
    raise IOError("%s not found." % path)
IOError: PARA_BTC_15M.csv not found.
```

**Comment by cooltheo17** [comment]
Everything should be fixed now. Thank you.
